baseURL = 'http://192.168.10.32:8081/'
languageCode = 'zh-cn'
title = 'Ziv的极客日志'
theme = 'PaperMod'

[params]
tocopen = true
author = "Ziv"
disableThemeToggle = false
showtoc = true
mainSections = ["posts"]