baseURL = 'https://bothubpr.github.io'
languageCode = 'zh-cn'
title = 'Ziv的极客日志'
theme = 'PaperMod'

[params]
tocopen = true
author = "Ziv"
disableThemeToggle = false
showtoc = true
mainSections = ["posts"]